### ISSUE TITLE
Add 1.19.2 compatibility

### ISSUE THREAD

**Issue by sylenthuntress** [eggohito/eggolib#23]
Eggolib does not currently seem to be compatible with 1.19.2.

> <html>Mod 'eggolib' (eggolib) 1.2.0 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present:<br>1.19.2!</html>

**Comment by eggohito** [comment]
Ah, I'm currently working on 1.3.0 that resolves this issue, but if needed, I can move the fix to 1.2.1 or release 1.3.0 early

**Comment by eggohito** [comment]
I've decided that I'll release 1.3.0 later to fix this issue

**Comment by eggohito** [comment]
Sorry for the delay, I'll be closing this now since I've finally released [1.3.0](https://github.com/eggohito/eggolib/releases/tag/v1.3.0-1.19)
