### ISSUE TITLE
[Suggestion] Add `prevent_key_use` power type

### ISSUE THREAD

**Issue by V-lpen** [eggohito/eggolib#24]
This could be used for many things, like restricting the player from using sneak in the deep dark, or preventing dismount from a player, or other uses, such as preventing attack when certain conditions are met, etc. 

Would look probably something like this?: 
{
	"type": "eggohito:prevent_key_use",
	"key": {
    "key": "key.sneak"
},
	"entity_condition": {
		"type": "origins:riding"
	}
}
Apologies if json is wrong, im on my phone-

**Comment by eggohito** [comment]
Thanks for the suggestion! I'll see what I can do

**Comment by eggohito** [comment]
I've now made progress with this suggestion, but I've been quite busy with school-work so it might take some more time

**Comment by eggohito** [comment]
This has now been implemented as of f494a7363535eaf8a381146e57e45c7078bae664
