### ISSUE TITLE
Major lag bug!

### ISSUE THREAD

**Issue by sylenthuntress** [eggohito/eggolib#25]
There is a MAJOR lag bug with this mod. While the mod is installed, servers will slowly, exponentially become laggier until they're unusable. This happens on both singleplayer and multiplayer, and there is nothing in logs to indicate this is happening. This happens whether the mod is being used or not, it just has to be installed.

**Comment by eggohito** [comment]
Hello! Can you test if this still persists in [eggolib v1.3.0](https://github.com/eggohito/eggolib/releases/tag/v1.3.0-1.19)? I've ran the Spark profiler in singleplayer and multiplayer *(PloudOS test server)* and there doesn't seem to be an impact regarding eggolib

**Comment by eggohito** [comment]
I'll take a look into this more. Also, can you test with spark via `/spark profiler` and let it run for a minute before stopping it with `/spark profiler --stop` and send the profiles here?

**Comment by sylenthuntress** [comment]
I forgot to check with spark before removing it, but the old bug didn't really persist. Instead, chunks and block updates weren't loading while the mod was installed.

**Comment by eggohito** [comment]
That is very strange... were there any warnings or errors in the output log? Are you sure this only happens with eggolib installed? A different mod might be causing it since eggolib doesn't touch chunk loading or block updates 🤔

**Comment by sylenthuntress** [comment]
No, and the issue didn't persist when the mod was removed. It may have been a weird symptom of a TPS issue caused by eggolib, combined with some other stuff on the server.

**Comment by eggohito** [comment]
Hmm. In that case, would you be able to test again but with Spark this time? Testing with and without eggolib and sending the Spark profiles here should suffice

**Comment by eggohito** [comment]
For anyone that's still experiencing this issue, providing Spark profiles of before/after removing eggolib would help quite a lot. Doing `/spark profiler` and letting it run for a minute or two before stopping it with `/spark profiler --stop` should suffice

**Comment by ChrysanthCow** [comment]
I'll be looking into this eventually, might even make a PR to help out.

**Comment by eggohito** [comment]
I've now released [eggolib v1.5.0](https://github.com/eggohito/eggolib/releases/tag/v1.5.0-1.19.3), which refactored the code for the syncing impl. of the `in_screen` entity condition type. Please try using that alongside Spark to see if the issue still persists

**Comment by eggohito** [comment]
To those who are still experiencing this issue, try using [this build](https://github.com/eggohito/eggolib/suites/14809024512/artifacts/842857485) of eggolib. One can adjust the value of the new `syncTickRate` config option in ModMenu (higher value = potentially less performance impact). Don't forget to also include Spark profiles when testing

**Comment by Lumi-Marcy** [comment]
no eggolib running on server or client (spark on client) - https://spark.lucko.me/YpvItXv3UU
eggolib running on both server and client - https://spark.lucko.me/FRXSIdDFNG

eggolib running on client in singleplayer - https://spark.lucko.me/9YXfiqv5Jh

personaly never had lag problems in single player with eggolib, but Ive included that just incase

also I got some screenshots of my ping in game while on the server with eggolib (ping display from minihud) I can send those in discord if you want them.
what they show is pretty much when I first logged in, minihud was displaying a ping of around 2300, after about 30 seconds that jumped to 7232, after another minute it jumped to 12264, then I got kicked a second or two after I took that screenshot.

**Comment by Lumi-Marcy** [comment]
tried that other build you recomended to try in the discord, with was with it on the server and client - https://spark.lucko.me/0PrEeMVtvX

ran way better, still not as good as without, where without eggolib I was averaging 2 ping and with I was averaging around 150, but its a huge step up from 12000

**Comment by eggohito** [comment]
[eggolib 1.9.1](https://github.com/eggohito/eggolib/releases/tag/v1.9.1-1.20) has now been released, which should fix this and a few other performance issues
