### ISSUE TITLE
Invisibility condition seems to work but doesn't ?

### ISSUE THREAD

**Issue by wirTosh** [eggohito/eggolib#43]
I could only notice this in multiplayer because it looks like it works on yourself, 
But actually it makes the player invisible constantly.
Am I missing something ? 

```
{
  "condition": {
    "inverted": true,
    "type": "origins:moving"
  },
  "type": "eggolib:invisibility",
  "render_armor": false,
}
```

Thank you again !

**Comment by eggohito** [comment]
This is more of an issue with the `origins:moving` entity condition type than an issue with the `eggolib:invisibility` power type

**Comment by wirTosh** [comment]
Ok now tested with `origins:sneaking` and it works as it should. It might even be the "inverted" but didn't test it.
Anyway it is not your mod's issue, Thanks !
