### ISSUE TITLE
eggolib:game_event_listener not working properly.

### ISSUE THREAD

**Issue by Scriptshatter** [eggohito/eggolib#45]
Whenever I try and use it, the console just spits out Cannot invoke "net.minecraft.class_1309.method_18376()" because "this.entity" is null

**Comment by eggohito** [comment]
Which version of eggolib are you using? That error in the output log shouldn't affect anything. It also should have been fixed in 1.4.1

**Comment by Scriptshatter** [comment]
Oh, I was using 1.4.0, since it's the latest version for 1.19.2. Personally, I think you should backport 1.4.1 to 1.19.2 (if it's not too much trouble), since it's what virtually every origins server uses.

**Comment by eggohito** [comment]
Closing this for now, as I don't really have the time to maintain multiple versions of eggolib for different versions of Minecraft. However, feel free to contribute if you want to backport features!
