### ISSUE TITLE
Eggolib v1.9.1 Breaks Tags added through NBT

### ISSUE THREAD

**Issue by Lilwhiteshark** [eggohito/eggolib#48]
`Eggolib v1.9.1`
`Fabric 0.15.6`
`Minecraft 1.20.1`

**Description:**
Adding a tag through NBT, such as with a summon command, does not tag the entity.

**More Details:**
Tags given to an already existing entity seem to work; for example:
1. `/summon armor_stand`
2. `/tag @e[type=armor_stand,limit=1] add exampletag`
3. `/execute as @e[type=armor_stand,tag=exampletag] run say Success!`
4. The Armor Stand tagged `exampletag` will say `Success!`

Tags given in NBT when summoning an entity DO NOT work, and appear to not tag the entity at all; for example:
1. `/summon armor_stand ~ ~ ~ {Tags:["exampletag"]}`
2. `/execute as @e[type=armor_stand,tag=exampletag] run say Success!`
3. No output
4. `/kill @e[type=armor_stand,tag=exampletag]`
5. Output: `No entity was found`

Tags worked as expected when reverting to `Eggolib v1.9.0`.

**Comment by eggohito** [comment]
Good catch! I'll release a fix later for 1.20.2, then do a backport

**Comment by eggohito** [comment]
This should now be fixed in [eggolib v1.10.2 (1.20 - 1.20.1)](https://github.com/eggohito/eggolib/releases/tag/v1.10.2-1.20) and [eggolib v1.10.2 (1.20.2)](https://github.com/eggohito/eggolib/releases/tag/v1.10.2-1.20.2)
